src/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('view/<int:pk>/', ProfileViewer.as_view(), name='profile_viewer')
]

src/profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profiles'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('', ProfileView.as_view(), name='profile_view'),
    path('update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('education/create', EducationCreateView.as_view(), name='education_create'),
    path('education/<int:pk>/update', EducationUpdateView.as_view(), name='education_update'),
    path('education/<int:pk>/delete', EducationDeleteView.as_view(), name='education_delete'),
    path('experience/create', ExperienceCreateView.as_view(), name='experience_create'),
    path('experience/<int:pk>/update', ExperienceUpdateView.as_view(), name='experience_update'),
    path('experience/<int:pk>/delete', ExperienceDeleteView.as_view(), name='experience_delete'),
    path('award/create', AwardCreateView.as_view(), name='award_create'),
    path('award/<int:pk>/update', AwardUpdateView.as_view(), name='award_update'),
    path('award/<int:pk>/delete', AwardDeleteView.as_view(), name='award_delete'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profiles.urls')),
    path('', include('posts.urls')),
]

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        ENLIGHTEN - WEBSITE
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- jQuery Import -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="crossorigin="anonymous"></script>
    <!-- Materialize JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
    <!-- Script JS -->
    <script src="{% static 'script.js' %}"></script>
    <!-- Materialize CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css" rel="stylesheet" type="text/css"/>
    <!-- Main CSS -->
    <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <!-- Material Icon -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 </head>
 <body>
    <nav>
        <div class="nav-wrapper white">
            <a href="{% url 'posts:post_list' %}" class="brand-logo teal-text" style="padding: 0px 20px"><i class="material-icons left">lightbulb_outline</i> ENLIGHTEN</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons teal-text">menu</i></a>
            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:post_list'%}" class="teal-text"><i class="material-icons left">home</i>Home</a></li>
                    <li><a href="{% url 'posts:post_create'%}" class="teal-text"><i class="material-icons left">edit</i>Post</a></li>
                    <li><a href="{% url 'profiles:profile_view'%}" class="teal-text"><i class="material-icons left">person</i>Profile</a></li>
                    <li><a href="{% url 'logout' %}" class="teal-text"><i class="material-icons left">power_settings_new</i>Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'profiles:register' %}" class="teal-text"><i class="material-icons left">person_add</i>Register</a></li>
                    <li><a href="{% url 'login' %}" class="teal-text"><i class="material-icons left">power_settings_new</i>Login</a></li>
                {% endif %}
            </ul>
            <ul class="side-nav white" id="mobile-demo">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:post_list'%}" class="teal-text"><i class="material-icons left">home</i>Home</a></li>
                    <li><a href="{% url 'posts:post_create'%}" class="teal-text"><i class="material-icons left">edit</i>Post</a></li> 
                    <li><a href="{% url 'profiles:profile_view'%}" class="teal-text"><i class="material-icons left">person</i>Profile</a></li>
                    <li><a href="{% url 'logout' %}" class="teal-text"><i class="material-icons left">power_settings_new</i>Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'profiles:register' %}" class="teal-text"><i class="material-icons left">person_add</i>Register</a></li>
                    <li><a href="{% url 'login' %}" class="teal-text"><i class="material-icons left">power_settings_new</i>Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}

        {% endblock content %}

        <br>
        <br>
    </div>
</body>
</html>