src/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('view/<int:pk>/', ProfileViewer.as_view(), name='profile_viewer')
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profiles.urls')),
    path('', include('posts.urls')),
]

src/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    title = models.CharField(max_length=100)
    text = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

src/posts/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    class Meta: 
        model = Post
        fields = ('title', 'text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'materialize-textarea'}),
        }

class CommentForm(forms.ModelForm):
    class Meta: 
        model = Post
        fields = ('text',)
        labels = {'text': 'Comment'}
        widgets = {
            'text': forms.Textarea(attrs={'class': 'materialize-textarea'}),
        }

src/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import *
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from .models import *
from profiles.models import Profile

class PostListView(LoginRequiredMixin, View):
    def get(self, request):
        post_list = Post.objects.order_by('-datetime')
        search = request.GET.get('q')
        if search:
            post_list = post_list.filter(Q(title__icontains=search) |
                                         Q(user__username__icontains=search) |
                                         Q(text__icontains=search)
                                        ).distinct()
        paginator = Paginator(post_list, 5)
        page = request.GET.get('page')
        posts = paginator.get_page(page)
        return render(request, 'posts/post_list.html', {'posts': posts})

class PostCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        return render(request, 'posts/post_create.html', {'form': form})

    def post(self, request):
        form = PostForm(request.POST or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('posts:post_list'))
        return render(request, 'posts/post_create.html', {'form': form})

class PostUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(instance=post)
        return render(request, 'posts/post_update.html', {'form': form})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('posts:post_detail', kwargs={'pk': pk}))
        return render(request, 'posts/post_update.html', {'form': form})


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):        
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'posts/post_delete.html', {'post': post})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return HttpResponseRedirect(reverse('posts:post_list'))

class PostUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(instance=post)
        return render(request, 'posts/post_update.html', {'form': form})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('posts:post_list'))
        return render(request, 'posts/post_update.html', {'form': form})


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):        
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'posts/post_delete.html', {'post': post})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return HttpResponseRedirect(reverse('posts:post_list'))

class ProfileViewer(LoginRequiredMixin, View):
    def get(self, request, pk):
        profile = get_object_or_404(Profile, pk=pk)
        if pk == request.user.profile.pk:
            return render(request, 'profiles/profile_view.html', {'profile': profile})
        return render(request, 'posts/profile_viewer.html', {'profile': profile})

src/templates/posts/post_create.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Create Post</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Post</button>
    <a class="btn red right" href="{% url 'posts:post_list' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/posts/post_delete.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <h1>Delete Post?     
        <span class="right">
            <button type="submit" class="btn red">YES</button>
            <a href="{% url 'posts:post_list'%}" class="btn blue">NO</a>
        </span>
    </h1>
</form>
<div class="row">
    <div class="col s12 m12">
        <div class="card teal">
            <div class="card-content white-text">
                <span class="card-title black-text">{{post.title}} <a class="amber-text" href="{% url 'posts:profile_viewer' pk=post.user.profile.pk %}">@{{post.user.username}}</a>
                    <span class="right">
                        {{post.datetime}}
                    </span>
                </span>
                <p>
                    {{post.text}}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/posts/post_list.html
{% extends "base.html" %}

{% block content %}
<br>
    <div class="row">
        <form class="col s12" method="GET">
            <div class="row">
                <div class="input-field col s12 m12">
                    <i class="material-icons prefix">search</i>
                    <input name="q" id="icon_prefix" type="text" class="validate" value='{{request.GET.q}}'>
                    <label for="icon_prefix">Search Enlighteners and Enlightenments</label>
                </div>
            </div>
        </form>
    </div>
    
{% if posts %}
    {% for post in posts %}
    <div class="row">
        <div class="col s12 m12">
            <div class="card teal">
                <div class="card-content white-text">
                    <span class="card-title black-text">{{post.title}} <a class="amber-text" href="{% url 'posts:profile_viewer' pk=post.user.profile.pk %}">@{{post.user.username}}</a>
                        <span class="right">
                            {{post.datetime}}
                        </span>
                    </span>
                    <p>
                        {{post.text}}
                    </p>
                </div>
                {% if user.id == post.user.id %}
                <div>
                    <div class="card-action">
                        <a class="amber-text" href="{% url 'posts:post_update' pk=post.pk %}">EDIT</a>
                        <a class="amber-text" href="{% url 'posts:post_delete' pk=post.pk %}">DELETE</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
    <p>No Posts</p>
{% endif %}


<div class="pagination" style="text-align: center">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}"><i class="material-icons black-text">chevron_left</i></a>
        {% endif %}

        <span class="current" style="font-size:30px">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}"><i class="material-icons black-text">chevron_right</i></a>
        {% endif %}
    </span>
</div

{% endblock content %}

src/templates/posts/post_update.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Update Post</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Update</button>
    <a class="btn red right" href="{% url 'posts:post_list' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/posts/profile_viewer.html
{% extends "base.html" %}

{% block content %}
<h1 class="black-text"> {{profile.fullname}} <small class="amber-text">@{{profile.user.username}}</small> </h1>

<div class="row">
    <div class="col s12 m12">
        <div class="card teal">
            <div class="card-content white-text">
                <span class="card-title">Biography</span>
                <p>
                    {{profile.biography}}
                </p>
            </div>
        </div>
    </div>
</div>

<h3 class="black-text">Education</h3>
{% if profile.user.education.all %}
    {% for education in profile.user.education.all %}
    <div class="row">
        <div class="col s12 m12">
            <div class="card teal">
                <div class="card-content white-text">
                    <span class="card-title">{{education.school}} - {{education.major}}
                        <span class="right">
                            {% if education.end_year %}
                            {{education.start_year}} - {{education.end_year}}
                            {% else %}
                            {{education.start_year}} - Present
                            {% endif %} 
                        </span>
                    </span>
                    <p>
                        {{education.activities}}
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
    <p>No Education</p>
{% endif %}


<h3 class="black-text">Experiences</h3>

{% if profile.user.experience.all %}
    {% for experience in profile.user.experience.all %}
    <div class="row">
        <div class="col s12 m12">
            <div class="card teal">
                <div class="card-content white-text">
                    <span class="card-title">{{experience.company}} - {{experience.position}}
                        <span class="right">
                            {% if experience.end_year %}
                            {{experience.start_year}} - {{experience.end_year}}
                            {% else %}
                            {{experience.start_year}} - Present
                            {% endif %} 
                        </span>
                    </span>
                    <p>
                        {{experience.description}}
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
    <p>No Experiences</p>
{% endif %}

<h3 class="black-text">Awards</h3>
{% if profile.user.award.all %}
    {% for award in profile.user.award.all %}
    <div class="row">
        <div class="col s12 m12">
            <div class="card teal">
                <div class="card-content white-text">
                    <span class="card-title">{{award.name}}
                        <span class="right">
                            {{award.year}}
                        </span>
                    </span>
                    <p>
                        {{award.description}}
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
    <p>No Awards</p>
{% endif %}       

{% endblock content %}