src/profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profiles'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('', ProfileView.as_view(), name='profile_view'),
    path('update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('education/create', EducationCreateView.as_view(), name='education_create'),
    path('education/<int:pk>/update', EducationUpdateView.as_view(), name='education_update'),
    path('education/<int:pk>/delete', EducationDeleteView.as_view(), name='education_delete'),
    path('experience/create', ExperienceCreateView.as_view(), name='experience_create'),
    path('experience/<int:pk>/update', ExperienceUpdateView.as_view(), name='experience_update'),
    path('experience/<int:pk>/delete', ExperienceDeleteView.as_view(), name='experience_delete'),
    path('award/create', AwardCreateView.as_view(), name='award_create'),
    path('award/<int:pk>/update', AwardUpdateView.as_view(), name='award_update'),
    path('award/<int:pk>/delete', AwardDeleteView.as_view(), name='award_delete'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profiles.urls')),
    path('', include('posts.urls')),
]

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    biography = models.TextField(null=True, blank=True)

    def fullname(self):
        return self.first_name + ' ' + self.last_name

    def __str__(self):
        return self.user.username

class Education(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='education')
    school = models.CharField(max_length=100)
    major = models.CharField(max_length=100)
    activities = models.TextField()
    start_year = models.CharField(max_length=4, validators=[MinLengthValidator(4)], null=True)
    end_year = models.CharField(max_length=4, validators=[MinLengthValidator(4)], null=True, blank=True)
    
    def __str__(self):
        return self.school

class Experience(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='experience')
    company = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    description = models.TextField()
    start_year = models.CharField(max_length=4, validators=[MinLengthValidator(4)], null=True)
    end_year = models.CharField(max_length=4, validators=[MinLengthValidator(4)], null=True, blank=True)

    def __str__(self):
        return self.company

class Award(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='award')
    name = models.CharField(max_length=100)
    description = models.TextField()
    year = models.CharField(max_length=4, validators=[MinLengthValidator(4)], null=True)
    
    def __str__(self):
        return self.name

src/profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *

class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
        self.fields['password2'].label = "Password Confirmation"

class ProfileForm(forms.ModelForm):
    class Meta: 
        model = Profile
        fields = ('first_name', 'last_name','email', 'biography')
        labels = {'first_name': 'First Name', 'last_name': 'Last Name'}
        widgets = {
            'biography': forms.Textarea(attrs={'class': 'materialize-textarea'}),
        }

class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ('school', 'major', 'activities', 'start_year', 'end_year')
        labels = {'start_year': 'Start Year', 'end_year': 'End Year'}
        widgets = {
            'activities': forms.Textarea(attrs={'class': 'materialize-textarea'}),
        }

class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ('company', 'position', 'description', 'start_year', 'end_year')
        labels = {'start_year': 'Start Year', 'end_year': 'End Year'}
        widgets = {
            'description': forms.Textarea(attrs={'class': 'materialize-textarea'}),
        }

class AwardForm(forms.ModelForm):
    class Meta:
        model = Award
        fields = ('name','year', 'description')
        labels = {'year': 'Year Received'}
        widgets = {
            'description': forms.Textarea(attrs={'class': 'materialize-textarea'}),
        }

src/profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.urls import reverse
from .forms import *
from .models import *

class RegisterView(View):
    def get(self, request):
        user = UserCreateForm()
        profile = ProfileForm()
        return render(request, 'profiles/register.html', {'user': user, 'profile': profile})

    def post(self, request):
        user = UserCreateForm(request.POST or None)
        profile = ProfileForm(request.POST or None)
        if user.is_valid() and profile.is_valid():
            user.save()
            profile.instance.user = user.instance
            profile.save()
            if user is not None:
                login(request, user.instance)
                return HttpResponseRedirect(reverse('posts:post_list'))
            return HttpResponseRedirect(reverse('login'))
        return render(request, 'profiles/register.html', {'user': user, 'profile': profile})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        profile = get_object_or_404(Profile, pk=request.user.profile.pk)
        return render(request, 'profiles/profile_view.html', {'profile': profile})

class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        profile = get_object_or_404(Profile, pk=request.user.profile.pk)
        form = ProfileForm(instance=profile)
        return render(request, 'profiles/profile_update.html', {'form': form})

    def post(self, request):
        profile = get_object_or_404(Profile, pk=request.user.profile.pk)
        form = ProfileForm(request.POST or None, instance=profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:profile_view'))
        return render(request, 'profiles/profile_update.html', {'form': form})

class EducationCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = EducationForm()
        return render(request, 'profiles/education_create.html', {'form': form})

    def post(self, request):
        form = EducationForm(request.POST or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('profiles:profile_view'))
        return render(request, 'profiles/education_create.html', {'form': form})

class EducationUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        education = get_object_or_404(Education, pk=pk)
        form = EducationForm(instance=education)
        return render(request, 'profiles/education_update.html', {'form': form})

    def post(self, request, pk):
        education = get_object_or_404(Education, pk=pk)
        form = EducationForm(request.POST or None, instance=education)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:profile_view'))
        return render(request, 'profiles/education_update.html', {'form': form})


class EducationDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):        
        education = get_object_or_404(Education, pk=pk)
        return render(request, 'profiles/education_delete.html', {'education': education})

    def post(self, request, pk):
        education = get_object_or_404(Education, pk=pk)
        education.delete()
        return HttpResponseRedirect(reverse('profiles:profile_view'))


class ExperienceCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = ExperienceForm()
        return render(request, 'profiles/experience_create.html', {'form': form})

    def post(self, request):
        form = ExperienceForm(request.POST or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('profiles:profile_view'))
        return render(request, 'profiles/experience_create.html', {'form': form})

class ExperienceUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        experience = get_object_or_404(Experience, pk=pk)
        form = ExperienceForm(instance=experience)
        return render(request, 'profiles/experience_update.html', {'form': form})

    def post(self, request, pk):
        experience = get_object_or_404(Experience, pk=pk)
        form = ExperienceForm(request.POST or None, instance=experience)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:profile_view'))
        return render(request, 'profiles/experience_update.html', {'form': form})


class ExperienceDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):
        experience = get_object_or_404(Experience, pk=pk)
        return render(request, 'profiles/experience_delete.html', {'experience': experience})

    def post(self, request, pk):
        experience = get_object_or_404(Experience, pk=pk)
        experience.delete()
        return HttpResponseRedirect(reverse('profiles:profile_view'))

class AwardCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = AwardForm()
        return render(request, 'profiles/award_create.html', {'form': form})

    def post(self, request):
        form = AwardForm(request.POST or None)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('profiles:profile_view'))
        return render(request, 'profiles/award_create.html', {'form': form})

class AwardUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        award = get_object_or_404(Award, pk=pk)
        form = AwardForm(instance=award)
        return render(request, 'profiles/award_update.html', {'form': form})

    def post(self, request, pk):
        award = get_object_or_404(Award, pk=pk)
        form = AwardForm(request.POST or None, instance=award)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profiles:profile_view'))
        return render(request, 'profiles/award_update.html', {'form': form})


class AwardDeleteView(LoginRequiredMixin, View):
    def get(self, request, pk):
        award = get_object_or_404(Award, pk=pk)
        return render(request, 'profiles/award_delete.html', {'award': award})

    def post(self, request, pk):
        award = get_object_or_404(Award, pk=pk)
        award.delete()
        return HttpResponseRedirect(reverse('profiles:profile_view'))

src/templates/profiles/award_create.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Add Award</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Add</button>
    <a class="btn red right" href="{% url 'profiles:profile_view' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/profiles/award_delete.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <h1>Delete Award?     
        <span class="right">
            <button type="submit" class="btn red">YES</button>
            <a href="{% url 'profiles:profile_view'%}" class="btn blue">NO</a>
        </span>
    </h1>
</form>
<div class="row">
    <div class="col s12 m12">
        <div class="card teal">
            <div class="card-content white-text">
                <span class="card-title">{{award.name}}
                    <span class="right">
                        {{award.year}}
                    </span>
                </span>
                <p>
                    {{award.description}}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/profiles/award_update.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Update Award</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Update</button>
    <a class="btn red right" href="{% url 'profiles:profile_view' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/profiles/education_create.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Add Education</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Add</button>
    <a class="btn red right" href="{% url 'profiles:profile_view' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/profiles/education_delete.html
{% extends "base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <h1>Delete Education?     
        <span class="right">
            <button type="submit" class="btn red">YES</button>
            <a href="{% url 'profiles:profile_view'%}" class="btn blue">NO</a>
        </span>
    </h1>
</form>
<div class="row">
    <div class="col s12 m12">
        <div class="card teal">
            <div class="card-content white-text">
                <span class="card-title">{{education.school}} - {{education.major}}
                    <span class="right">
                        {% if education.end_year %}
                        {{education.start_year}} - {{education.end_year}}
                        {% else %}
                        {{education.start_year}} - Present
                        {% endif %} 
                    </span>
                </span>
                <p>
                    {{education.activities}}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/profiles/education_update.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Update Education</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Update</button>
    <a class="btn red right" href="{% url 'profiles:profile_view' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/profiles/experience_create.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Add Work Experience</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Add</button>
    <a class="btn red right" href="{% url 'profiles:profile_view' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/profiles/experience_delete.html
{% extends "base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <h1>Delete Work Experience?     
        <span class="right">
            <button type="submit" class="btn red">YES</button>
            <a href="{% url 'profiles:profile_view'%}" class="btn blue">NO</a>
        </span>
    </h1>
</form>
<div class="row">
    <div class="col s12 m12">
        <div class="card teal">
            <div class="card-content white-text">
                <span class="card-title">{{experience.company}} - {{experience.position}}
                    <span class="right">
                        {% if experience.end_year %}
                        {{experience.start_year}} - {{experience.end_year}}
                        {% else %}
                        {{experience.start_year}} - Present
                        {% endif %} 
                    </span>
                </span>
                <p>
                    {{experience.description}}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/templates/profiles/experience_update.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Update Work Experience</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Update</button>
    <a class="btn red right" href="{% url 'profiles:profile_view' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/profiles/profile_update.html
{% extends "base.html" %}
{% load material_form %}

{% block content %}
<h1>Update Profile</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=form %}{% endform %}
    <button type="submit" class="btn">Update</button>
    <a class="btn red right" href="{% url 'profiles:profile_view' %}">Cancel</a>
</form>
{% endblock content %}

src/templates/profiles/profile_view.html
{% extends "base.html" %}

{% block content %}
<div class="fixed-action-btn toolbar">
    <a class="btn-floating btn-large black">
        <i class="large material-icons white-text">add</i>
    </a>
    <ul>
        <li class="waves-effect waves-light"><a href="{% url 'profiles:education_create' %}"><span class="white-text">EDUCATION</span></a></li>
        <li class="waves-effect waves-light"><a href="{% url 'profiles:experience_create' %}"><span class="white-text">EXPERIENCES</span></a></li>
        <li class="waves-effect waves-light"><a href="{% url 'profiles:award_create' %}"><span class="white-text">AWARDS</span></a></li>
    </ul>
</div>

<h1 class="black-text"> {{profile.fullname}} <small class="amber-text">@{{profile.user.username}}</small> </h1>

<div class="row">
    <div class="col s12 m12">
        <div class="card teal">
            <div class="card-content white-text">
                <span class="card-title">Biography</span>
                <p>
                    {{profile.biography}}
                </p>
            </div>
            <div class="card-action">
                <a class="amber-text" href="{% url 'profiles:profile_update' %}">EDIT</a>
            </div>
        </div>
    </div>
</div>

<h3 class="black-text">Education</h3>
{% if profile.user.education.all  %}
    {% for education in profile.user.education.all %}
        <div class="row">
            <div class="col s12 m12">
                <div class="card teal">
                    <div class="card-content white-text">
                        <span class="card-title">{{education.school}} - {{education.major}}
                            <span class="right">
                                {% if education.end_year %}
                                {{education.start_year}} - {{education.end_year}}
                                {% else %}
                                {{education.start_year}} - Present
                                {% endif %} 
                            </span>
                        </span>
                        <p>
                            {{education.activities}}
                        </p>
                    </div>
                    <div class="card-action">
                        <a class="amber-text" href="{% url 'profiles:education_update' pk=education.pk %}">EDIT</a>
                        <a class="amber-text" href="{% url 'profiles:education_delete' pk=education.pk %}">DELETE</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <a href="{% url 'profiles:education_create' %}" class="btn teal">Add an Education</a>
{% endif %}




<h3 class="black-text">Experiences</h3>

{% if  profile.user.experience.all%}
    {% for experience in profile.user.experience.all %}
        <div class="row">
            <div class="col s12 m12">
                <div class="card teal">
                    <div class="card-content white-text">
                        <span class="card-title">{{experience.company}} - {{experience.position}}
                            <span class="right">
                                {% if experience.end_year %}
                                {{experience.start_year}} - {{experience.end_year}}
                                {% else %}
                                {{experience.start_year}} - Present
                                {% endif %} 
                            </span>
                        </span>
                        <p>
                            {{experience.description}}
                        </p>
                    </div>
                    <div class="card-action">
                        <a class="amber-text" href="{% url 'profiles:experience_update' pk=experience.pk %}">EDIT</a>
                        <a class="amber-text" href="{% url 'profiles:experience_delete' pk=experience.pk %}">DELETE</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <a href="{% url 'profiles:experience_create' %}" class="btn teal">Add a Work Experience</a>
{% endif %}



<h3 class="black-text">Awards</h3>

{% if profile.user.award.all%}
    {% for award in profile.user.award.all %}
        <div class="row">
            <div class="col s12 m12">
                <div class="card teal">
                    <div class="card-content white-text">
                        <span class="card-title">{{award.name}}
                            <span class="right">
                                {{award.year}}
                            </span>
                        </span>
                        <p>
                            {{award.description}}
                        </p>
                    </div>
                    <div class="card-action">
                        <a class="amber-text" href="{% url 'profiles:award_update' pk=award.pk %}">EDIT</a>
                        <a class="amber-text" href="{% url 'profiles:award_delete' pk=award.pk %}">DELETE</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <a href="{% url 'profiles:award_create' %}" class="btn teal">Add an Award</a>
{% endif %}

            
{% endblock content %}

src/templates/profiles/register.html
{% extends "base.html" %}
{% load material_form  %}

{% block content %}
<h1>Register</h1>
<form method="POST">
    {% csrf_token %}
    {% form form=user %}{% endform %}
    {% form form=profile %}{% endform %}
    <button type="submit" class="btn">Register</button>
</form>
{% endblock content %}